### ISSUE TITLE
Solved: [Patch & Image] for 1.18 until a pull request comes through.

### ISSUE THREAD

**Issue by hchasens** [Phyremaster/papermc-docker#65] opened 2021-12-02 00:05 UTC
Pull request #64 solves this. I compiled and image and it's available [here](https://hub.docker.com/r/hchasens/papermc). I'm not maintaining this and you should switch back as soon as @Phyremaster merges the pull request!

I know this isn't a 'Issue' but anyone having this issue might look here. Please close upon merge. Thank you and sorry for the misuse of this the Issues tab.

**Comment by Area45** [comment] 2021-12-11 20:36
I found this helpful, thanks so much!

Not sure if this'll help anyone but I made a quick copy of @hchasens build but I built it for arm64 and confirmed it working on an arm based Mac available [here](https://hub.docker.com/r/sassychan/papermcarm). I agree to switch back as soon as the pull request is merged.

**Comment by Captain-Reginald** [comment] 2022-01-07 23:02
I get the error `Error response from daemon: manifest for hchasens/papermc:latest not found: manifest unknown: manifest unknown` when trying to pull your version. I can pull `phyremaster/papermc` just fine though... any idea what the problem might be? I'm still pretty new to docker.

**Comment by hchasens** [comment] 2022-01-07 23:10
@Captain-Reginald Try pulling 'hchasens/papermc:1.18.1' exactly. I've not tagged any 'latest' so you're getting the docker equivalent of a 404. (This was to communicate that the repo would not be maintained) If you'd like an example there's a 'docker-compose.yml' in the description of the docker repo.

**Comment by Captain-Reginald** [comment] 2022-01-07 23:13
> @Captain-Reginald Try pulling 'hchasens/papermc:1.18.1' exactly. I've not tagged any 'latest' so you're getting the docker equivalent of a 404. (This was to communicate that the repo would not be maintained) If you'd like an example there's a 'docker-compose.yml' in the description of the docker repo.

Hmm, I just did that but got the same response. It's insisting on continuing to use the latest tag even though I haven't specified that in the command.

**Comment by hchasens** [comment] 2022-01-07 23:19
I'll be able to talk in 30 minutes. My email is on my profile. If you email me your discord or phone number I'll be happy to provide some tech support 😁. I'll then post the solution here or, if needed, open a new issue. Does this work for you?

**Comment by Captain-Reginald** [comment] 2022-01-07 23:22
> I'll be able to talk in 30 minutes. My email is on my profile. If you email me your discord or phone number I'll be happy to provide some tech support 😁. I'll then post the solution here or, if needed, open a new issue. Does this work for you?

Unfortunately I'll be busy this evening starting right around then, haha. Would you be at all available any time on Sunday?

**Comment by hchasens** [comment] 2022-01-07 23:29
I should be. Email me and we'll workout scheduling. In the meantime can you post your:

Computer Type/Specs
OS Type and Version
Docker Version

And your start script/command along with the output

**Comment by Captain-Reginald** [comment] 2022-01-07 23:43
Emailed you a bit ago. :)

My computer is a repurposed desktop that I've turned into a server. 

Specs are:
AMD Phenom II x6 1055T processor
28 GB of RAM
GTX 560 GPU (just for graphics output when I'm not logging in via ssh)
256 GB SSD boot drive with three 500 GB HDDs in RAID-z as a ZFS pool
Host OS is TrueNAS SCALE (brand new to that)

I tried running docker natively, but I get an error saying my jar file is corrupt - no idea why. The same containers work fine outside of TrueNAS. As such I'm currently working with a virtualized version of Ubuntu Server 20.04.3 LTS.

Docker version is 20.10.7.

**Comment by hchasens** [comment] 2022-01-08 00:00
Thank you. I just successfully pulled the repo from another system. It sounds like a config issue more than anything. I'll be happy to help. What's your start command/script?

**Comment by Captain-Reginald** [comment] 2022-01-08 00:02
Sorry about leaving off the script, I just edited the comment to include it.

**Comment by hchasens** [comment] 2022-01-08 00:44
I think the issue is with your start script. I think I confused you with a pervious comment about versions. Try using this command. 

`sudo docker run -p 25565:25565 -v /mnt/zpool1/minecraft/papermc/test:/papermc -d -it --restart on-failure --name "papermc-1.18.1" -e MC_RAM="4G" hchasens/papermc:1.18.1`

For debugging it also helps to avoid detaching the container, this way you can see it's output. A detached version would be.
 
`sudo docker run -p 25565:25565 -v /mnt/zpool1/minecraft/papermc/test:/papermc -it --restart on-failure --name "papermc-1.18.1" -e MC_RAM="4G" hchasens/papermc:1.18.1`

I tested this on my Mac (with a modified volume argument) and it worked fine.

**Comment by Captain-Reginald** [comment] 2022-01-09 18:45
Just for public record, the problem is solved. I couldn't pull the image because it was pulling the tag `latest` when that wasn't specified. Fixed with `docker pull hchasens/papermc:1.18.1`

Thanks again for your help!

**Comment by lonyelon** [comment] 2022-02-09 15:28
> Pull request #64 solves this. I compiled and image and it's available [here](https://hub.docker.com/r/hchasens/papermc). I'm not maintaining this and you should switch back as soon as @Phyremaster merges the pull request!
> 
> I know this isn't a 'Issue' but anyone having this issue might look here. Please close upon merge. Thank you and sorry for the misuse of this the Issues tab.

Very useful, thanks a lot!

**Comment by Phyremaster** [comment] 2023-09-08 02:20
Holy shit. I can't believe I let this slide for so long. My apologies to everyone who's been inconvenienced by this over the past few years, and my thanks to everyone who has provided workarounds and alternatives during this time.

I just merged #72 which has the side effect of fixing this. Please let me know if anything breaks, because clearly telling myself that I have to test every PR personally was a terrible idea; I haven't used Docker directly for game servers for years and never set up a testing environment. I will create a discussion with further information.

**Closed by Phyremaster** 2023-09-08 02:20 UTC
